/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Dados.Paciente;
import Funcionarios.Secretaria;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.swing.JOptionPane;

public class AtualizaDadosPaciente extends javax.swing.JFrame {
    Paciente pac;
    String cpf;
    Secretaria sec;
    EntityManager em;
    
    /**
     * Creates new form AtualizaDadosPaciente
     * @param sec
     * @param em
     */
    public AtualizaDadosPaciente(Secretaria sec, EntityManager em) {
        initComponents();
        this.sec = sec;
        this.em = em;
        initPaciente(); // Preenche os campos da tela com as informações do paciente
        //Fatores estéticos da janela (tamanho, posição e cor)
        setSize(480, 450);
        setLocationRelativeTo(null);
        getContentPane().setBackground(java.awt.Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        convenioNovo = new javax.swing.JCheckBox();
        nomeNovo = new javax.swing.JTextField();
        idadeNovo = new javax.swing.JTextField();
        enderecoNovo = new javax.swing.JTextField();
        telefoneNovo = new javax.swing.JTextField();
        emailNovo = new javax.swing.JTextField();
        feminino = new javax.swing.JRadioButton();
        masculino = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(165, 107, 255));
        jLabel1.setText("ATUALIZAÇÃO - DADOS PACIENTE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 40));

        jLabel2.setText("Preencha somente os campos que deseja alterar.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel3.setText("Os campos não preenchidos manterão seus antigos valores.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Nome:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 60, 20));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Idade:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 60, 20));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Sexo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 60, 20));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Endereço:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 80, 20));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Telefone:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 60, 20));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("E-mail:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 60, 20));

        convenioNovo.setBackground(new java.awt.Color(255, 255, 255));
        convenioNovo.setText("Paciente de convênio");
        getContentPane().add(convenioNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));
        getContentPane().add(nomeNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 290, -1));
        getContentPane().add(idadeNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 90, -1));
        getContentPane().add(enderecoNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 290, -1));
        getContentPane().add(telefoneNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 290, -1));
        getContentPane().add(emailNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 290, -1));

        feminino.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(feminino);
        feminino.setText("Feminino");
        getContentPane().add(feminino, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        masculino.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(masculino);
        masculino.setText("Masculino");
        getContentPane().add(masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        jLabel4.setText("Se nenhum campo foi alterado, cancele a operação.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, 20));

        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jButton2.setBackground(new java.awt.Color(224, 188, 255));
        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarAlteracoes(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar
        /*
        Cancela a ação.
        */
        dispose();
    }//GEN-LAST:event_cancelar

    private void salvarAlteracoes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarAlteracoes
        /*
        A secretária altera os dados do paciente determinado e a tela de atualização é fechada.
        Os dados de todos os campos são levados para atualização, mesmo que eles não tenham sido alterados.
        */
        char sexo = 'N';
        
        //DEFINIÇÃO DO CHAR SEXO
        if (feminino.isSelected()) { //Verifica se o sexo escolhido foi o botão FEMININO
            sexo = 'F';
        } else {
            if(masculino.isSelected()) { //Verifica se foi o botão MASCULINO
                sexo = 'M';
            }
        }
        //SECRETARIA ATUALIZA OS DADOS DO PACIENTE TIRADOS DOS CAMPOS
        em.getTransaction().begin();
        sec.atualizarPaciente(pac, nomeNovo.getText(), sexo, Integer.parseInt(idadeNovo.getText()), enderecoNovo.getText(), telefoneNovo.getText(), emailNovo.getText(), convenioNovo.isSelected());
        em.getTransaction().commit();
        dispose();
    }//GEN-LAST:event_salvarAlteracoes

    private void initPaciente() {
        /*
        Pega as informações atuais do paciente e preenche os campos com elas.
        Caso haja alteração, o campo pode ser modificado, caso não, ele permanece com a informação original.
        */
        this.cpf = JOptionPane.showInputDialog(null, "Insira o CPF do paciente:", "Identificar Paciente", JOptionPane.QUESTION_MESSAGE);
        
        em.getTransaction().begin();
        //BUSCA O PACIENTE DE cpf NO BANCO DE DADOS
        Query query = em.createQuery(("select p FROM Paciente p WHERE p.cpf LIKE \'" + cpf + "\'"));
        List<Paciente> pacientes = query.getResultList();
        pac = pacientes.get(0);
        em.getTransaction().commit();
        
        //Iniciando os campos com as informações do paciente:
        nomeNovo.setText(pac.getNome());
        idadeNovo.setText(pac.getIdade() + ""); // Transforma o inteiro em string para o campo de texto.
        enderecoNovo.setText(pac.getEndereco());
        telefoneNovo.setText(pac.getTelefone());
        emailNovo.setText(pac.getEmail());
        convenioNovo.setSelected(pac.getConvenio());
        
        if (pac.getSexo() == 'F') {
            feminino.setSelected(true);
        } else {
            if (pac.getSexo() == 'M') {
                masculino.setSelected(true); 
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox convenioNovo;
    private javax.swing.JTextField emailNovo;
    private javax.swing.JTextField enderecoNovo;
    private javax.swing.JRadioButton feminino;
    private javax.swing.JTextField idadeNovo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton masculino;
    private javax.swing.JTextField nomeNovo;
    private javax.swing.JTextField telefoneNovo;
    // End of variables declaration//GEN-END:variables
}
