/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Dados.Consulta;
import Dados.Paciente;
import Funcionarios.CadastroMedico;
import Funcionarios.Medico;

/**
 *
 * @author home
 */
public class AtualizaDadosSaudePaciente extends javax.swing.JFrame {
    Medico med;
    Paciente pac;
    
    /**
     * Creates new form AtualizaDadosSaudePaciente
     * @param med
     * @param pac
     */
    public AtualizaDadosSaudePaciente(Medico med, Paciente pac) {
        initComponents();
        this.med = med;
        this.pac = pac;
        initPaciente();
        setSize(470, 345);
        setLocationRelativeTo(null);
        getContentPane().setBackground(java.awt.Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Salvar = new javax.swing.JButton();
        fumar = new javax.swing.JCheckBox();
        beber = new javax.swing.JCheckBox();
        colesterol = new javax.swing.JCheckBox();
        diabetes = new javax.swing.JCheckBox();
        cardio = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        alergias = new javax.swing.JScrollPane();
        alergiasPac = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        cirurgias = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salvar.setBackground(new java.awt.Color(179, 242, 255));
        Salvar.setText("Salvar");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });
        getContentPane().add(Salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        fumar.setText("Fuma?");
        getContentPane().add(fumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        beber.setText("Ingere bebidas alcoólicas?");
        getContentPane().add(beber, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        colesterol.setText("Tem colesterol alto?");
        getContentPane().add(colesterol, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        diabetes.setText("Tem diabetes?");
        getContentPane().add(diabetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        cardio.setText("Possui alguma doença cardiovascular?");
        getContentPane().add(cardio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(107, 211, 255));
        jLabel1.setText("ATUALIZAÇÃO - FICHA MÉDICA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel2.setText("Cirurgias:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 20));

        jLabel3.setText("Alergias:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 20));

        alergiasPac.setColumns(20);
        alergiasPac.setRows(5);
        alergias.setViewportView(alergiasPac);

        getContentPane().add(alergias, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 320, 40));

        cirurgias.setColumns(20);
        cirurgias.setRows(5);
        jScrollPane2.setViewportView(cirurgias);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 320, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar
        /*
        Cancela a ação.
        */
        dispose();
    }//GEN-LAST:event_cancelar

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        /*
        O medico atualiza a ficha medica do paciente em consulta com as informações dos campos.
        Todos os campos sempre são atualizados, mesmo que a informação neles não tenha sido alterada
        */
        
        med.atualizarPaciente(pac, fumar.isSelected(), beber.isSelected(), colesterol.isSelected(), diabetes.isSelected(), cardio.isSelected(), alergiasPac.getText(), cirurgias.getText());
        dispose();
    }//GEN-LAST:event_SalvarActionPerformed

    private void initPaciente() {
        /*
        Preenche os campos com os dados do paciente.
        Permite que o médico verifique quais eram os dados anteriores.
        */
        fumar.setSelected(pac.isFumar());
        beber.setSelected(pac.isBeber());
        cardio.setSelected(pac.isDoencaCardio());
        colesterol.setSelected(pac.isColesterol());
        diabetes.setSelected(pac.isDiabete());
        cirurgias.setText(pac.getCirurgias());
        alergiasPac.setText(pac.getAlergias());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salvar;
    private javax.swing.JScrollPane alergias;
    private javax.swing.JTextArea alergiasPac;
    private javax.swing.JCheckBox beber;
    private javax.swing.JCheckBox cardio;
    private javax.swing.JTextArea cirurgias;
    private javax.swing.JCheckBox colesterol;
    private javax.swing.JCheckBox diabetes;
    private javax.swing.JCheckBox fumar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
