/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Funcionarios.Medico;
import javax.swing.JOptionPane;

/**
 *
 * @author guijo
 */
public class CadastraDadosSaudePaciente extends javax.swing.JFrame {
    Medico med;
    
    /**
     * Creates new form CadastraDadosSaudePaciente
     * @param med
     */
    public CadastraDadosSaudePaciente(Medico med) {
        this.med = med;
        initComponents();
        setSize(485, 380);
        setLocationRelativeTo(null);
        getContentPane().setBackground(java.awt.Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Salvar = new javax.swing.JButton();
        fumar = new javax.swing.JCheckBox();
        beber = new javax.swing.JCheckBox();
        colesterol = new javax.swing.JCheckBox();
        diabetes = new javax.swing.JCheckBox();
        cardio = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        identificaConsulta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alergias = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        cirurgias = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clinica Medica");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(107, 211, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO - FICHA MÉDICA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, 60));

        Salvar.setBackground(new java.awt.Color(179, 242, 255));
        Salvar.setText("Salvar");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });
        getContentPane().add(Salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        fumar.setText("Fuma?");
        getContentPane().add(fumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        beber.setText("Ingere bebidas alcoólicas?");
        getContentPane().add(beber, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        colesterol.setText("Tem colesterol alto?");
        getContentPane().add(colesterol, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        diabetes.setText("Tem diabetes?");
        getContentPane().add(diabetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        cardio.setText("Possui alguma doença cardiovascular?");
        getContentPane().add(cardio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel2.setText("Insira a data e o horário da consulta:");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 20));
        getContentPane().add(identificaConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 180, -1));

        jLabel3.setText("Cirurgias?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 20));

        jLabel4.setText("Alergias?");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));

        alergias.setColumns(20);
        alergias.setRows(5);
        jScrollPane1.setViewportView(alergias);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 310, 40));

        cirurgias.setColumns(20);
        cirurgias.setRows(5);
        jScrollPane2.setViewportView(cirurgias);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 310, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        /*
        O medico cadastra a ficha medica do paciente em consulta com as informações dos campos.
        */
    
        med.cadastrarDadosPaciente((identificaConsulta.getText() + med.getCrm()), fumar.isSelected(), beber.isSelected(), colesterol.isSelected(), diabetes.isSelected(), cardio.isSelected(), cirurgias.getText(), alergias.getText());
        
        dispose();
    }//GEN-LAST:event_SalvarActionPerformed

    private void cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar
        /*
        Cancela a ação.
        */
        dispose();
    }//GEN-LAST:event_cancelar

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salvar;
    private javax.swing.JTextArea alergias;
    private javax.swing.JCheckBox beber;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cardio;
    private javax.swing.JTextArea cirurgias;
    private javax.swing.JCheckBox colesterol;
    private javax.swing.JCheckBox diabetes;
    private javax.swing.JCheckBox fumar;
    private javax.swing.JTextField identificaConsulta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
