/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Funcionarios.Medico;
import javax.swing.JOptionPane;

/**
 *
 * @author guijo
 */
public class CadastraDadosSaudePaciente extends javax.swing.JFrame {
    Medico med;
    
    /**
     * Creates new form CadastraDadosSaudePaciente
     * @param med
     */
    public CadastraDadosSaudePaciente(Medico med) {
        this.med = med;
        initComponents();
        setSize(485, 370);
        setLocationRelativeTo(null);
        getContentPane().setBackground(java.awt.Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        alergiasNum = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cirurgiasNum = new javax.swing.JComboBox<>();
        Salvar = new javax.swing.JButton();
        fumar = new javax.swing.JCheckBox();
        beber = new javax.swing.JCheckBox();
        colesterol = new javax.swing.JCheckBox();
        diabetes = new javax.swing.JCheckBox();
        cardio = new javax.swing.JCheckBox();
        cirurgiasTF = new javax.swing.JCheckBox();
        alergiasTF = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        identificaConsulta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clinica Medica");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(107, 211, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO - FICHA MÉDICA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, 60));

        alergiasNum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "20+" }));
        alergiasNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alergiasNumActionPerformed(evt);
            }
        });
        getContentPane().add(alergiasNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        jLabel8.setText("Quantas:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 49, 20));

        jLabel10.setText("Quantas:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 49, 20));

        cirurgiasNum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "20+" }));
        cirurgiasNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cirurgiasNumActionPerformed(evt);
            }
        });
        getContentPane().add(cirurgiasNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        Salvar.setBackground(new java.awt.Color(179, 242, 255));
        Salvar.setText("Salvar");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });
        getContentPane().add(Salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        fumar.setText("Fuma?");
        getContentPane().add(fumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        beber.setText("Ingere bebidas alcoólicas?");
        getContentPane().add(beber, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        colesterol.setText("Tem colesterol alto?");
        getContentPane().add(colesterol, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        diabetes.setText("Tem diabetes?");
        getContentPane().add(diabetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        cardio.setText("Possui alguma doença cardiovascular?");
        getContentPane().add(cardio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        cirurgiasTF.setText("Tem alguma cirurgia?");
        getContentPane().add(cirurgiasTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        alergiasTF.setText("Possui alergias?");
        getContentPane().add(alergiasTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLabel2.setText("Insira a data, o horario e seu CRM:");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 20));
        getContentPane().add(identificaConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        /*
        O medico cadastra a ficha medica do paciente em consulta com as informações dos campos.
        */
        String cirurgias = "";
        String alergias = "";

        med.cadastrarDadosPaciente(identificaConsulta.getText(), fumar.isSelected(), beber.isSelected(), colesterol.isSelected(), diabetes.isSelected(), cardio.isSelected(), cirurgias, alergias);
        
        dispose();
    }//GEN-LAST:event_SalvarActionPerformed

    private void cirurgiasNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cirurgiasNumActionPerformed
        /*
        Caso um número de cirurgias diferente de 0 (default) seja selecionado, abre uma janela para que elas sejam inseridas.
        */
        String cirurgias = JOptionPane.showInputDialog(null, "Digite uma de suas cirurgias:", "Cirurgias",JOptionPane.QUESTION_MESSAGE);
        
    }//GEN-LAST:event_cirurgiasNumActionPerformed

    private void alergiasNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alergiasNumActionPerformed
        /*
        Caso um número de alergias diferente de 0 (default) seja selecionado, abre uma janela para que elas sejam inseridas.
        */
        String alergias = JOptionPane.showInputDialog(null, "Digite uma de suas alergias:", "Alergias",JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_alergiasNumActionPerformed

    private void cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar
        /*
        Cancela a ação.
        */
        dispose();
    }//GEN-LAST:event_cancelar

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salvar;
    private javax.swing.JComboBox<String> alergiasNum;
    private javax.swing.JCheckBox alergiasTF;
    private javax.swing.JCheckBox beber;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cardio;
    private javax.swing.JComboBox<String> cirurgiasNum;
    private javax.swing.JCheckBox cirurgiasTF;
    private javax.swing.JCheckBox colesterol;
    private javax.swing.JCheckBox diabetes;
    private javax.swing.JCheckBox fumar;
    private javax.swing.JTextField identificaConsulta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
