/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Funcionarios.Secretaria;

/**
 *
 * @author home
 */
public class CadastroPaciente extends javax.swing.JFrame {
    private Secretaria sec;
    
    /**
     * Creates new form CadastroPaciente
     * @param sec
     */
    public CadastroPaciente(Secretaria sec) {
        initComponents();
        setSize(540, 450);
        setLocationRelativeTo(null);
        getContentPane().setBackground(java.awt.Color.white);
        this.sec = sec;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        cpf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rg = new javax.swing.JTextField();
        idade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        telefone = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        endereco = new javax.swing.JTextField();
        feminino = new javax.swing.JRadioButton();
        masculino = new javax.swing.JRadioButton();
        dataNascimento = new javax.swing.JTextField();
        convenio = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clinica Medica");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(165, 107, 255));
        jLabel1.setText("CADASTRO - PACIENTE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nome completo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 100, 20));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("CPF (xxx.xxx.xxx-xx):");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 20));
        getContentPane().add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 300, -1));
        getContentPane().add(cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 300, -1));

        jLabel4.setText("Data de Nascimento:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, 20));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Endereço:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 60, 20));
        getContentPane().add(rg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 300, -1));
        getContentPane().add(idade, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 50, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Telefone:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 60, 20));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("E-mail:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 60, 20));
        getContentPane().add(telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 300, -1));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 300, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("RG (xx.xxx.xxx-x):");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 100, 20));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Sexo:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 100, 20));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Idade:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 100, 20));
        getContentPane().add(endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 300, -1));

        buttonGroup1.add(feminino);
        feminino.setText("Feminino");
        getContentPane().add(feminino, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        buttonGroup1.add(masculino);
        masculino.setText("Masculino");
        getContentPane().add(masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));
        getContentPane().add(dataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 110, -1));

        convenio.setText("Paciente de convênio");
        getContentPane().add(convenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 140, -1));

        jButton1.setBackground(new java.awt.Color(224, 188, 255));
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarPaciente(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, -1));

        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarCadastro(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarPaciente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarPaciente
        /*
        Envia os dados inseridos do paciente para a secretária executar o cadastro dele no banco de dados da clínica.
        */
        int idadeInt = Integer.parseInt(idade.getText());
        char sexo = 'N'; //Inicia como 'N' para "não informado"
        if (feminino.isSelected()) { //Verifica se o sexo escolhido foi o botão FEMININO
            sexo = 'F';
        } else {
            if(masculino.isSelected()) { //Verifica se foi o botão MASCULINO
                sexo = 'M';
            }
        }
        //OBJETO SECRETÁRIA CADASTRA O PACIENTE NO BANCO DE DADOS
        sec.cadastrarPaciente(nome.getText(), cpf.getText(), rg.getText(), sexo, idadeInt, dataNascimento.getText(), endereco.getText(), telefone.getText(), email.getText(), convenio.isSelected());
        dispose();
    }//GEN-LAST:event_cadastrarPaciente

    private void cancelarCadastro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarCadastro
        // TODO add your handling code here:
        dispose(); //setVisible(false); ???
    }//GEN-LAST:event_cancelarCadastro
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox convenio;
    private javax.swing.JTextField cpf;
    private javax.swing.JTextField dataNascimento;
    private javax.swing.JTextField email;
    private javax.swing.JTextField endereco;
    private javax.swing.JRadioButton feminino;
    private javax.swing.JTextField idade;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton masculino;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField rg;
    private javax.swing.JTextField telefone;
    // End of variables declaration//GEN-END:variables
}
