/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Funcionarios.CadastroMedico;
import Funcionarios.Medico;
import Funcionarios.Secretaria;
import static java.lang.System.exit;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Query;
import javax.swing.JOptionPane;

public class MenuPrincipal extends javax.swing.JFrame {
    EntityManager em;
    /**
     * Creates new form MenuPrincipal
     * @param em
     */
    public MenuPrincipal(EntityManager em) {
        initComponents();
        this.em = em; //traz o gerenciador de entidades
        //Fatores estéticos da janela (tamanho, posição e cor)
        setSize(540, 320);
        setLocationRelativeTo(null);
        getContentPane().setBackground(java.awt.Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Clinica Medica");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(165, 107, 255));
        jButton1.setText("SECRETÁRIA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSecretaria(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 150, 70));

        jButton2.setBackground(new java.awt.Color(107, 211, 255));
        jButton2.setText("MÉDICO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acharMedico(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 150, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Selecione o tipo de usuário:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 180, 30));

        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActioPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSecretaria(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSecretaria
        /* 
        Se o usuário escolher o modo secretária, ele será direcionado ao menu da secretária.
        Há apenas uma secretária e, portanto, não há necessidade de procurar sua identificação no banco de dados
        */
        // Única secretária / único objeto secretária do sistema
        Secretaria sec = new Secretaria("Maria Gabriela", "123.123.123-44", 4.500, em);
        
        // Verificação do usuário
        String nome = JOptionPane.showInputDialog(null, "Insira o usuário:", "Identificação",JOptionPane.QUESTION_MESSAGE);
        // Caso o usuário cancele a JOptionPane, a string nome será null -> nada acontece.
        if (nome != null) {
            if ((sec.getNome().toUpperCase()).equals(nome.toUpperCase())) { // Se o nome da secretária estiver correto:
                dispose(); //A tela do menu principal é invisibilizada
                // A tela do menu da secretária passa a ser a visível para alterações pelo objeto secretária
                new MenuSecretaria(sec, em).setVisible(true);
            } else { // Se não:
                // o usuário é desconhecido
                JOptionPane.showMessageDialog(null, "Usuário desconhecido!", "Identificação", JOptionPane.WARNING_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_menuSecretaria

    private void acharMedico(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acharMedico
        /*
        Recupera o objeto CadastroMedico correto do Banco de Dados e instancia o médico correto para ações.
        */
        //Verificação do usuário
        String crm = JOptionPane.showInputDialog(null, "Insira seu CRM:", "Identificação",JOptionPane.QUESTION_MESSAGE);
        //Caso o usuário cancele a JOptionPane, a string crm será null -> nada acontece.
        if(crm != null) {
            try{
                em.getTransaction().begin();
                // BUSCA O CADASTRO DO MÉDICO DO crm INSERIDO
                Query query = em.createQuery(("select m FROM CadastroMedico m WHERE m.crm LIKE \'" + crm + "\'"));
                List<CadastroMedico> medico = query.getResultList();
                em.getTransaction().commit();

                CadastroMedico certo = medico.get(0); // CRM é uma informação única -> será o da posição 0
                if (certo.getCrm().equals(crm)) { // confere se é o crm correto, se é:
                    dispose();
                    //Cria um objeto médico com as informações retiradas do cadastro
                    Medico med = new Medico(certo.getNome(), certo.getCrm(), certo.getCpf(), certo.getSalario(), certo.getAtendimentos(), em);
                    new MenuMedico(med, em).setVisible(true); //vai ao menu de médicos
                }
            }
            catch(IndexOutOfBoundsException e){ //Exceção: caso o CRM inserido não seja encontrado
                // Mostra uma mensagem de que o usuário não foi reconhecido
                JOptionPane.showMessageDialog(null, "Usuário desconhecido! CRM inválido.", "Identificação", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_acharMedico

    private void sairActioPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActioPerformed
        /*
        Para sair do menu principal, o unuário deve encerrar o programa pelo botão "Sair" sempre.
        */
        EntityManagerFactory emf = em.getEntityManagerFactory();
        em.close();
        emf.close();
        exit(0);     
    }//GEN-LAST:event_sairActioPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
