/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Dados.Paciente;
import Funcionarios.CadastroMedico;
import Funcionarios.Medico;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.swing.JOptionPane;

public class MenuMedico extends javax.swing.JFrame {
    Medico med;
    EntityManager em;
    
    /**
     * Creates new form MenuMedico
     * @param med
     * @param em
     */
    public MenuMedico(Medico med, EntityManager em) {
        this.med = med;
        this.em = em;
        initComponents();
        //Fatores estéticos da janela (tamanho, posição e cor)
        setSize(640, 450);
        setLocationRelativeTo(null);
        getContentPane().setBackground(java.awt.Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cadastraFichaMedica = new javax.swing.JButton();
        atualizaFichaMedica = new javax.swing.JButton();
        cadastrarProntuario = new javax.swing.JButton();
        atualizaProntuario = new javax.swing.JButton();
        removeProntuario = new javax.swing.JButton();
        geraRelatorios = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clinica Medica");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(107, 211, 255));
        jLabel1.setText("MENU MÉDICO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 240, 60));

        cadastraFichaMedica.setBackground(new java.awt.Color(179, 242, 255));
        cadastraFichaMedica.setText("Cadastrar Ficha Médica");
        cadastraFichaMedica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFichaMédicaActionPerformed(evt);
            }
        });
        getContentPane().add(cadastraFichaMedica, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 240, -1));

        atualizaFichaMedica.setBackground(new java.awt.Color(179, 242, 255));
        atualizaFichaMedica.setText("Atualizar Ficha Médica");
        atualizaFichaMedica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarFichaMedica(evt);
            }
        });
        getContentPane().add(atualizaFichaMedica, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 240, -1));

        cadastrarProntuario.setBackground(new java.awt.Color(179, 242, 255));
        cadastrarProntuario.setText("Cadastrar Prontuário");
        cadastrarProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarProntuarioActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarProntuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 240, -1));

        atualizaProntuario.setBackground(new java.awt.Color(179, 242, 255));
        atualizaProntuario.setText("Atualizar Prontuário");
        atualizaProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizaProntuario(evt);
            }
        });
        getContentPane().add(atualizaProntuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 240, -1));

        removeProntuario.setBackground(new java.awt.Color(179, 242, 255));
        removeProntuario.setText("Remover Prontuário");
        removeProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerProntuario(evt);
            }
        });
        getContentPane().add(removeProntuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 240, -1));

        geraRelatorios.setBackground(new java.awt.Color(179, 242, 255));
        geraRelatorios.setText("Gerar Relatório");
        geraRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarRelatorio(evt);
            }
        });
        getContentPane().add(geraRelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 240, -1));

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 0, 0));
        jButton7.setText("Sair");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sair(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair
        /*
        Volta para o menu principal -> "saindo" do login do usuário.
        Ao sair do login do médico a lista de atendimentos é atualizada no cadastro do médico.
        Pois, durente o uso, ela pode ter sido alterada (com novas consultas a novos pacientes)
        */
        em.getTransaction().begin();
        //BUSCA O OBJETO CADASTROMEDICO RELACIONADO AO OBJETO MEDICO USANDO O SISTEMA ATUALMENTE
        Query query = em.createQuery(("select m FROM CadastroMedico m WHERE m.crm LIKE \'" + med.getCrm() + "\'"));
        List<CadastroMedico> certo = query.getResultList();
        
        certo.get(0).setAtendimentos(med.getPacientesAtendidos()); // ATUALIZA A LISTA DE ATENDIMENTOS RELACIONADAS AO MEDICO -> POIS NOVAS CONSULTAS PODEM TER SIDO REALIZADAS
        em.getTransaction().commit();
        
        dispose();
        new MenuPrincipal(em).setVisible(true);
    }//GEN-LAST:event_sair

    private void gerarRelatorio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarRelatorio
        /*
        Leva ao menu de relatórios que podem ser gerados pelo médico
        */
        new MenuRelatorios(med).setVisible(true);
    }//GEN-LAST:event_gerarRelatorio

    private void cadastrarFichaMédicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFichaMédicaActionPerformed
        /*
        Leva à tela de cadastro da ficha médica de um paciente.
        */
        new CadastraDadosSaudePaciente(med).setVisible(true);
    }//GEN-LAST:event_cadastrarFichaMédicaActionPerformed

    private void cadastrarProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarProntuarioActionPerformed
        /*
        Leva à tela de cadastro do prontuário de um paciente.
        */
        new CadastraProntuario(med).setVisible(true);
    }//GEN-LAST:event_cadastrarProntuarioActionPerformed

    private void removerProntuario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerProntuario
        /*
        O médico remove o prontuário de um paciente a partir do seu CPF.
        */
        //OBTEM O cpf DO PACIENTE PARA REMOÇÃO DO PRONTUÁRIO
        String cpf = JOptionPane.showInputDialog(null, "Insira o CPF do paciente para remover o prontuário:", "REMOÇÃO DO PRONTUÁRIO", JOptionPane.INFORMATION_MESSAGE);
                
        med.removerProntuario(cpf); // CHAMA O MÉTODO DO MÉDICO PARA REMOVER O PRONTUÁRIO DO PACIENTE
    }//GEN-LAST:event_removerProntuario

    private void atualizarFichaMedica(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarFichaMedica
        /*
        Leva à tela de atualizar a ficha médica
        */
        // Pega o cpf do paciente que vai ser alterado
        String cpf = JOptionPane.showInputDialog(null, "Insira o CPF do paciente para remover o prontuário:", "REMOÇÃO DO PRONTUÁRIO", JOptionPane.INFORMATION_MESSAGE);
        em.getTransaction().begin();
        //BUSCA O PACIENTE CORRETO NO BANCO DE DADOS
        Query query = em.createQuery(("select p FROM Paciente p WHERE p.cpf LIKE \'" + cpf + "\'"));
        List<Paciente> pac = query.getResultList(); // O CPF é único para cada paciente. Portanto, o paciente correto estará no índice 0.
        
        new AtualizaDadosSaudePaciente(med, pac.get(0)).setVisible(true);
        em.getTransaction().commit();
    }//GEN-LAST:event_atualizarFichaMedica

    private void atualizaProntuario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizaProntuario
        /*
        Leva à tela de atualização do prontuário do paciente de CPF 'cpf'.
        */
        //Pega o cpf do paciente que vai ter o prontuário alterado
        String cpf = JOptionPane.showInputDialog(null, "Insira o CPF do paciente para remover o prontuário:", "REMOÇÃO DO PRONTUÁRIO", JOptionPane.INFORMATION_MESSAGE);
        em.getTransaction().begin();
        // BUSCA O PACIENTE CORRETO NO BANCO DE DADOS
        Query query = em.createQuery(("select p FROM Paciente p WHERE p.cpf LIKE \'" + cpf + "\'"));
        List<Paciente> pac = query.getResultList(); // O CPF é único para cada paciente. Portanto, o paciente correto estará no índice 0.
        
        new AtualizaProntuario(med, pac.get(0)).setVisible(true);
        em.getTransaction().commit();
    }//GEN-LAST:event_atualizaProntuario

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizaFichaMedica;
    private javax.swing.JButton atualizaProntuario;
    private javax.swing.JButton cadastraFichaMedica;
    private javax.swing.JButton cadastrarProntuario;
    private javax.swing.JButton geraRelatorios;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton removeProntuario;
    // End of variables declaration//GEN-END:variables
}
