/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author home
 */
public class MenuSecretaria extends javax.swing.JFrame {

    /**
     * Creates new form MenuSecretaria
     */
    public MenuSecretaria() {
        initComponents();
        setSize(640, 480);
        setLocationRelativeTo(null);
        getContentPane().setBackground(java.awt.Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clinica Medica");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(224, 188, 255));
        jButton1.setText("Novo Paciente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarPaciente(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 240, -1));

        jButton2.setBackground(new java.awt.Color(224, 188, 255));
        jButton2.setText("Remover Paciente");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 240, -1));

        jButton3.setBackground(new java.awt.Color(224, 188, 255));
        jButton3.setText("Atualizar Dados - Paciente");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 240, -1));

        jButton4.setBackground(new java.awt.Color(224, 188, 255));
        jButton4.setText("Nova Consulta");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 240, -1));

        jButton5.setBackground(new java.awt.Color(224, 188, 255));
        jButton5.setText("Atualizar Data e Hora - Consulta");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 240, -1));

        jButton6.setBackground(new java.awt.Color(224, 188, 255));
        jButton6.setText("Remover Consulta");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 240, -1));

        jButton7.setBackground(new java.awt.Color(224, 188, 255));
        jButton7.setText("Gerenciar Consultas - Dia Seguinte");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 240, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(165, 107, 255));
        jLabel1.setText("MENU SECRETÁRIA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 170, 50));

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 0, 0));
        jButton8.setText("Sair");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarPaciente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarPaciente
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarPaciente

    private void sair(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair
        /*
        Volta para o menu principal -> "saindo" do login do usuário.
        */
        setVisible(false);
        new MenuPrincipal().setVisible(true);
    }//GEN-LAST:event_sair



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
