/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author home
 */
public class MenuMedico extends javax.swing.JFrame {

    /**
     * Creates new form MenuMedico
     */
    public MenuMedico() {
        initComponents();
        setSize(640, 450);
        setLocationRelativeTo(null);
        getContentPane().setBackground(java.awt.Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CadastraFichaMédica = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        CadastrarProntuario = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clinica Medica");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(107, 211, 255));
        jLabel1.setText("MENU MÉDICO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 130, 60));

        CadastraFichaMédica.setBackground(new java.awt.Color(179, 242, 255));
        CadastraFichaMédica.setText("Cadastrar Ficha Médica");
        CadastraFichaMédica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFichaMédicaActionPerformed(evt);
            }
        });
        getContentPane().add(CadastraFichaMédica, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 240, -1));

        jButton2.setBackground(new java.awt.Color(179, 242, 255));
        jButton2.setText("Atualizar Ficha Médica");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 240, -1));

        CadastrarProntuario.setBackground(new java.awt.Color(179, 242, 255));
        CadastrarProntuario.setText("Cadastrar Prontuário");
        CadastrarProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarProntuarioActionPerformed(evt);
            }
        });
        getContentPane().add(CadastrarProntuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 240, -1));

        jButton4.setBackground(new java.awt.Color(179, 242, 255));
        jButton4.setText("Atualizar Prontuário");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 240, -1));

        jButton5.setBackground(new java.awt.Color(179, 242, 255));
        jButton5.setText("Remover Prontuário");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 240, -1));

        jButton6.setBackground(new java.awt.Color(179, 242, 255));
        jButton6.setText("Gerar Relatório");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarRelatorio(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 240, -1));

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 0, 0));
        jButton7.setText("Sair");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sair(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair
        /*
        Volta para o menu principal -> "saindo" do login do usuário.
        */
        dispose();
        new MenuPrincipal().setVisible(true);
    }//GEN-LAST:event_sair

    private void gerarRelatorio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarRelatorio
        /*
        Leva ao menu de relatórios que podem ser gerados.
        */
        new MenuRelatorios().setVisible(true);
    }//GEN-LAST:event_gerarRelatorio

    private void cadastrarFichaMédicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFichaMédicaActionPerformed
        /*
        Leva à tela de cadastro da ficha médica de um paciente.
        */
        new CadastraDadosSaudePaciente().setVisible(true);
    }//GEN-LAST:event_cadastrarFichaMédicaActionPerformed

    private void cadastrarProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarProntuarioActionPerformed
        /*
        Leva à tela de cadastro do prontuário de um paciente.
        */
        new CadastraProntuario().setVisible(true);
    }//GEN-LAST:event_cadastrarProntuarioActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastraFichaMédica;
    private javax.swing.JButton CadastrarProntuario;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
