/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author home
 */
public class MenuRelatorios extends javax.swing.JFrame {

    /**
     * Creates new form GerarRelatorios
     */
    public MenuRelatorios() {
        initComponents();
        setSize(300, 300); //tamanho fixo da janela
        setLocationRelativeTo(null); //abertura no meio da tela
        getContentPane().setBackground(java.awt.Color.white); //cor de fundo : branco
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(107, 211, 255));
        jLabel1.setText("RELATÓRIOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jButton1.setBackground(new java.awt.Color(179, 242, 255));
        jButton1.setText("Atestado");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 210, -1));

        jButton2.setBackground(new java.awt.Color(179, 242, 255));
        jButton2.setText("Declaração de Acompanhamento");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 210, -1));

        jButton3.setBackground(new java.awt.Color(179, 242, 255));
        jButton3.setText("Receita");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 210, -1));

        jButton4.setBackground(new java.awt.Color(179, 242, 255));
        jButton4.setText("Relação de clientes atendidos");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 210, -1));

        jButton5.setForeground(new java.awt.Color(255, 0, 0));
        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarRelatorio(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarRelatorio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarRelatorio
        // TODO add your handling code here:
        setVisible(false);
        new MenuMedico().setVisible(true);
    }//GEN-LAST:event_cancelarRelatorio

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
