/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Funcionarios.Medico;

/**
 *
 * @author home
 */
public class MenuRelatorios extends javax.swing.JFrame {
    Medico med;
    /**
     * Creates new form GerarRelatorios
     * @param med
     */
    public MenuRelatorios(Medico med) {
        this.med = med;
        initComponents();
        setSize(300, 300); //tamanho fixo da janela
        setLocationRelativeTo(null); //abertura no meio da tela
        getContentPane().setBackground(java.awt.Color.white); //cor de fundo : branco
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clinica Medica");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(107, 211, 255));
        jLabel1.setText("RELATÓRIOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, 40));

        jButton1.setBackground(new java.awt.Color(179, 242, 255));
        jButton1.setText("Atestado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarAtestado(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 210, -1));

        jButton2.setBackground(new java.awt.Color(179, 242, 255));
        jButton2.setText("Declaração de Acompanhamento");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarDeclaracao(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 210, -1));

        jButton3.setBackground(new java.awt.Color(179, 242, 255));
        jButton3.setText("Receita");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarReceita(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 210, -1));

        jButton4.setBackground(new java.awt.Color(179, 242, 255));
        jButton4.setText("Relação de clientes atendidos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesAtendidos(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 210, -1));

        jButton5.setForeground(new java.awt.Color(255, 0, 0));
        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarRelatorio(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarRelatorio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarRelatorio
        /*
        Cancela a ação.
        */
        dispose();
    }//GEN-LAST:event_cancelarRelatorio

    private void clientesAtendidos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesAtendidos
        /*
        Leva à tela para consulta do número de clientes atendidos.
        */
        new TelaClientesAtendidos(med).setVisible(true);
    }//GEN-LAST:event_clientesAtendidos

    private void gerarAtestado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarAtestado
        /*
        Leva à tela de atestados.
        */
        new TelaAtestado(med).setVisible(true);
    }//GEN-LAST:event_gerarAtestado

    private void gerarDeclaracao(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarDeclaracao
        /*
        Leva à tela de declarações de acompanhamento.
        */
        new TelaDeclaracao(med).setVisible(true);
    }//GEN-LAST:event_gerarDeclaracao

    private void gerarReceita(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarReceita
        /*
        Leva à tela de receitas.
        */
        new TelaReceita(med).setVisible(true);
    }//GEN-LAST:event_gerarReceita

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
