/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Funcionarios.Secretaria;
import javax.persistence.EntityManager;

/**
 *
 * @author home
 */
public class NovaConsulta extends javax.swing.JFrame {
    Secretaria sec;
    /**
     * Creates new form NovaConsulta
     * @param sec
     */
    public NovaConsulta(Secretaria sec) {
        initComponents();
        setSize(480, 280);
        setLocationRelativeTo(null);
        getContentPane().setBackground(java.awt.Color.white);
        this.sec =  sec;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        data = new javax.swing.JTextField();
        hora = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        retorno = new javax.swing.JCheckBox();
        cpfPaciente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        crmMedico = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clinica Medica");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(165, 107, 255));
        jLabel1.setText("CADASTRO - NOVA CONSULTA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel2.setText("Data:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 20));

        jLabel3.setText("Horário:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, 20));
        getContentPane().add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 110, -1));
        getContentPane().add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 120, -1));

        jLabel4.setText("Médico (CRM):");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 20));

        retorno.setText("Consulta de retorno");
        getContentPane().add(retorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));
        getContentPane().add(cpfPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 230, -1));

        jLabel5.setText("Paciente (CPF):");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 20));

        jButton1.setBackground(new java.awt.Color(224, 188, 255));
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarConsulta(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarCadastro(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));
        getContentPane().add(crmMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarConsulta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarConsulta
        /*
        A secretária cadastra a nova consulta no banco de dados com as informações dos campos.
        */
        char ret;
        if (retorno.isSelected()) {
            ret = 'R';
        } else {
            ret = 'N';
        }
        
        sec.cadastrarConsulta(data.getText(), hora.getText(), crmMedico.getText(), cpfPaciente.getText(), ret);
    }//GEN-LAST:event_cadastrarConsulta

    private void cancelarCadastro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarCadastro
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelarCadastro

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cpfPaciente;
    private javax.swing.JTextField crmMedico;
    private javax.swing.JTextField data;
    private javax.swing.JTextField hora;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JCheckBox retorno;
    // End of variables declaration//GEN-END:variables
}
