/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Funcionarios.Medico;

/**
 *
 * @author home
 */
public class TelaClientesAtendidos extends javax.swing.JFrame {
    Medico med;
    /**
     * Creates new form TelaClientesAtendidos
     * @param med
     */
    public TelaClientesAtendidos(Medico med) {
        this.med = med;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mes = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ano = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 71, -1));

        jLabel1.setText("Mês da consulta:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));
        getContentPane().add(ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 70, -1));

        jLabel2.setText("Ano da consulta:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(107, 211, 255));
        jLabel3.setText("CONSULTAR NÚMERO DE CLIENTES ATENDIDOS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jButton2.setBackground(new java.awt.Color(179, 242, 255));
        jButton2.setText("Consultar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarClientes(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar
        /*
        Cancela a ação.
        */
        dispose();
    }//GEN-LAST:event_cancelar

    private void consultarClientes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarClientes
        /*
        Consultar o número de clientes atendidos no mês do ano preenchidos nos campos.
        */
        med.clientesAtendidos(Integer.parseInt(mes.getText()), Integer.parseInt(ano.getText()));
    }//GEN-LAST:event_consultarClientes

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ano;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField mes;
    // End of variables declaration//GEN-END:variables
}
